src/components/Badge/Badge.jsx
src/components/Badge/Badge.module.css
src/components/Badge/index.js
src/pages/sample/components/SolSample.jsx

- close #31 
- 답변 상태 뱃지 컴포넌트 (답변 완료/미답변)
- answer변수에 api를 통해 들어오는 데이터 형식 그대로를 담았습니다. (예시코드)
- status에 completed(답변 완료), incomplete(미답변) 상태 값을 보냅니다.
- status 값에 따라 badgeData 변수에 저장된 라벨명, 색상코드 값들이 출력 됩니다.

Feat: 답변상태 Badge 컴포넌트 개발

---

src/components/Modal/Modal.jsx
src/components/Modal/Modal.module.css
src/components/Modal/index.js
src/components/Modal/usePreventScroll.js
src/pages/sample/components/SolSample.jsx

- close #36
- 모달 마크업
- 모달 닫기/열기 기능 구현
- 모달창 열렸을 때 스크롤 막기 구현
- pc
- mobile
- 모달 아이콘과 모달 타이틀을 넘겨주지 않으면 모달창 상단에 닫기 버튼만 보입니다.
- 모달창 닫기 이벤트는 모달창 외부 클릭과 닫기 버튼 클릭 두 곳에서 일어납니다.
- 브라우저 크기에 비해 모달창 콘텐츠가 넘칠 경우에는 내부 스크롤이 생성되도록 스타일 잡았습니다.
-  모달창이 열릴 때 브라우저 전체 스크롤을 막고 닫힐 때 스크롤이 원래 위치로 복구 됩니다.
- 스크롤 막기/해제 부분은 usePreventScroll.js에 커스텀 훅으로 빼놓았습니다.
- 다른 페이지에서도 활용 가능합니다.

Feat(#36): 공통 컴포넌트 - 모달 개발 (SOL)

---

src/components/Reaction/Reaction.jsx
src/components/Reaction/Reaction.module.css
src/components/Reaction/index.js
src/pages/sample/components/ChankiSample.jsx
src/pages/sample/components/ChankiSample.module.css

- close #28 
- 좋아요, 싫어요 버튼 컴포넌트 작업했습니다.
- 좋아요, 싫어요 버튼은 카운트가 1이상이면 각각의 색상으로 활성화 상태를 나타냈습니다.
- 기본적인 button의 props도 전달받을수 있게 작업했습니다.
- 버튼에 hover시 엄지가 흔들리는 keyframe 애니메이션 추가했어요
https://github.com/user-attachments/assets/9dba8cf7-2914-4369-9a0f-124b22682026
- 좋아요 버튼, 싫어요 버튼을 마구마구 누르면 계속 각각 카운트가 올라가는게 맞는것 같아요. (익명이라)
- 위 내용은 나중에 페이지 작업할때 또 의논해보면 좋을것 같아요
- 그저 좋아요버튼의 파란색과, 싫어요 버튼의 검은색은 카운트가 1이상이냐에만 초점을 뒀습니다.

Feat(#28): reaction 컴포넌트 추가

---

src/pages/post/components/PostDetailHeader.jsx
src/pages/post/loader/PostDetailLoader.js
src/router.jsx

- close #64
아래 페이지에서 공유하게 될 피드 정보 데이터를 react router의 loader로 받아서
useLoaderData, useRouteLoaderData 훅을 통해서 사용할수 있습니다.
- 한솔님이 작업하시는 헤더 파일안에서 const data = useLoaderData(); 이렇게 사용해서 데이터를 가져오면 됩니다.
- 원리는 react router의 loader입니다.
- '/post' 주소를 타고갈때, loader를 실행해서 데이터를 미리받아서 주입시켜주는 원리입니다.
- loader함수에는 방정보를 가져오는 api 호출이 담겨있고, 나중에 유섭님이 api 추상화 완료하시면 교체할께요
- loader가 가져온 데이터를 useLoaderData라는 함수로 가져와서 쓰는 방식입니다. (약간 context api같은 느낌이욤)
- useLoaderData는 react router의 훅입니당

Feat(#64): PostDetail loader 추가

---

src/components/Avatar/Avatar.jsx

- close #60 
avatar 컴포넌트에 기본 이미지가 나오는 케이스들을 점검하고 추가했습니다.
- src를 누락한경우
- src에 빈문자를 전달한경우
- src의 주소로 이미지를 불러오는데 실패한 경우

Fix(#60): avatar 컴포넌트에 src가 누락됬을경우에도 기본 이미지가 나오게 설정

---

src/pages/main/MainPage.jsx
src/pages/main/MainPage.module.css
src/pages/main/components/MainLogo.jsx
src/pages/main/components/MainLogo.module.css
src/pages/main/components/Sample.jsx
src/pages/main/components/Sample.module.css

- close #77 
- MainLogo 컴포넌트에 로고이미지를 중앙에 위치하게 구현
- 뷰크기에 따라 로고이미지 크기 변경
https://github.com/user-attachments/assets/6b4572e9-366e-4970-a498-0196f172d95a
- 수정할 사항 알려주시면 다시 수정하겠습니다!

Feat(#77): 메인로고 컴포넌트 반응형 구현

---

src/components/FeedCard/Answer.jsx
src/components/FeedCard/Answer.module.css
src/components/FeedCard/AnswerForm.jsx
src/components/FeedCard/AnswerForm.module.css
src/components/FeedCard/FeedCard.jsx
src/components/FeedCard/FeedCardWrapper.jsx
src/components/FeedCard/FeedCardWrapper.module.css
src/components/FeedCard/Question.jsx
src/components/FeedCard/Question.module.css
src/components/FeedCard/Reactions.jsx
src/components/FeedCard/Reactions.module.css
src/components/FeedCard/index.js
src/pages/sample/components/ChankiSample.jsx
src/pages/sample/components/ChankiSample.module.css
src/util/format.js

- close #62 
- 피드 상세페이지에서 사용되는 질문카드를 작업했습니다.
- 질문카드 내부에 들어가는 컴포넌트들을 분리해서 작업했습니다.
- 카드 외형 컴포넌트 (카드 껍데기, 카드 푸터 껍데기)
- 상단 질문 컴포넌트
- 답변자 정보 컴포넌트
- 답변 컴포넌트
- 답변 입력/수정 컴포넌트
버튼 공용컴포넌트가 완성되면 교체 예정입니다. 
임시로 css작업해두었어요

Feat(#62) feed card 컴포넌트 작업

---

src/pages/post/components/PostList.jsx
src/pages/post/components/PostList.module.css

- close #82 
-질문자 목록 리스트를 위한 api 호출 및 데이터 받기 테스트
페이지 작업을 세분화 해서 이슈를 만들었는데 단순 함수 호출만 이렇게 만들어도 되는지 의문이 드네요
질문자 목록 조회만 해도 UserCard, Pagination, Select 컴포넌트 연결이 가능할 것 같아서 혹시 이상한곳이 있으면 수정 바로 하겠습니다!

Feat(#): PostList 페이지 질문자목록 조회 api 연결

---

package-lock.json
package.json
src/App.jsx
src/assets/img/common/icon_empty.svg
src/components/FeedCard/Answer.jsx
src/components/FeedCard/AnswerForm.jsx
src/components/FeedCard/FeedCard.jsx
src/components/FeedCard/FeedCardWrapper.module.css
src/components/FeedCard/Question.jsx
src/pages/post/PostAnswerPage.jsx
src/pages/post/PostDetailPage.jsx
src/pages/post/components/PostMessage.jsx
src/pages/post/components/PostMessage.module.css
src/pages/post/components/QuestionForm.jsx
src/pages/post/components/QuestionForm.module.css
src/pages/post/components/Questions.jsx
src/pages/post/components/Questions.module.css
src/pages/post/components/useAnswer.js
src/pages/post/components/useLike.js
src/pages/post/components/useQuestion.js
src/pages/post/components/useQuestions.js

- close #84 
- close #93 
- close #94 
- close #95 
- close #96 
상세페이지 작업을 1차적으로 했습니다.
- 질문 리스트 조회 (무한스크롤)
- 질문 작성
- 질문 및 답변 리스트 조회 (무한스크롤)
- 답변 작성/수정/거절/삭제
프리뷰url에서 아래 주소를 확인하시면 결과를 보실수있어요
- https://deploy-preview-97--openmind-sprint12.netlify.app/post/9281
- https://deploy-preview-97--openmind-sprint12.netlify.app/post/9281/answer
- 이어서 반응형 css와 추가적인 개선사항도 더 작업 예정입니다.
- 버튼 공용컴포넌트 완성되면 교체도 해야되구욤
- 리액트쿼리 너무 좋은것 같네요...
- 공식문서가 너무 잘되어있어서 별로 어렵지않게 사용했습니다.
- 한솔님이 만들어주신 모달, 토스트 팝업덕분에 빨리 끝났습니다.

Feat(#84, #93, #94, #95, #96): 피드 상세페이지 작업 

---

src/pages/post/components/PostList.jsx
src/pages/post/components/PostList.module.css
src/pages/post/components/itemPerPage.js

- close #109 
-Select 컴포넌트를 사용하여 PostList페이지 최신순/이름순 정렬기능 구현 및 css 스타일링
-페이지 새로고침 시 화면사이즈에 맞게 usercard 갯수가 설정되지 않아서 화면사이즈 확인 후 itemperpage
를 세팅해주는 함수를 외부에서 가져오게 따로 만들었습니다.
- 잘못된 질문자 목록
- 수정 후
페이지에서 화면 사이즈 확인 후 가져올 질문자 목록 수를 정하는것보다 외부에서 만들어
페이지 함수 시작전에 체크하는게 맞는지 모르겠습니다. 일단 동작은 하는것같아요

Feat(#109): PostList 페이지 Dropdown 컴포넌트 연결 sort기능 구현

---

src/components/Dropdown/MoreMenu.module.css
src/pages/sample/components/ChankiSample.jsx

- close #134
MoreMenu의 항목들에 disabled가 있을경우의 css를 추가했습니다.
(select는 만들었는데, Moremenu쪽이 빠졋네요)
- 투명도 조절 및 not-allowed 마우스커서로 변경

Design(#134) : dropdown css 개선

---

src/components/FeedCard/Answer.jsx
src/components/FeedCard/AnswerButton.jsx
src/components/FeedCard/AnswerButton.module.css
src/components/FeedCard/AnswerMenu.jsx
src/components/FeedCard/FeedCard.jsx
src/components/FeedCard/QuestionForm.jsx
src/components/FeedCard/Reactions.jsx
src/components/FeedCard/index.js
src/context/FeedContext.jsx
src/main.jsx
src/pages/post/PostAnswerPage.jsx
src/pages/post/PostDetailPage.jsx
src/pages/post/components/Questions.jsx
src/pages/post/components/useQuestion.js
src/pages/post/components/useQuestionHandlers.js

- close #129 
피드카드 내부에 들어있는 데이터 핸들링 훅들을 하나의 통합된 훅으로 모아서
질문, 답편 페이지 진입부에서 선언하여, 리스트 컴포넌트에게 주입하는 형식으로 개선했습니다.
- 컴포넌트들이 데이터 랜더링에만 집중할 수 있도록 개선했어요
- 훅을 이용해 피드 주인이면 답변하러가기 버튼이 보이도록 했어요
- main.jsx에서 reset,global의 임포트 순서가 app.jsx보다 밑이라서 스타일 오버라이딩이 되지않아 수정해두었습니다. (a tag 스타일링을 하는데 우선순위가 잘못되어있어서 적용이 안되더군욧)

Refactor(#129): 질문, 답변 페이지 리팩토링 (훅 재정비)

---

src/context/FeedContext.jsx
src/pages/post/PostDetailPage.jsx

- close #139 
- 기존에 만든 useFeed 컨텍스트에 기능을 추가했습니다.
- visited : 최근방문 리스트
- saveVisited : 최근방문 리스트 저장 함수
- clearVisited : 최근방문 리스트 삭제 함수
- /post/{subjectId} 으로 접속시에 saveVisted를 통해 최근방문리스트에 추가하는 행동을 작성해두었습니다.
- 메인이나, 다른페이지에서 최근방문기록을 사용하실분은 useFeed 컨텍스트에서 visited, clearVisited를 꺼내서 활용하시면 됩니다.
- visited : 최근방문 리스트
- clearVisited : 최근방문 삭제 기능
- 모든 함수에 useCallback을 적용해두었습니다. (혹시나 이 함수를 의존성배열에 넣게 되면 무한랜더링 루프 방지를 위해)

Feat(#139): 질문리스트페이지(/post/{subjectId}) 접속시 최근방문 로그 저장

---

src/pages/post/components/PostList.jsx

- close #147
- 화면 사이즈 변경 시 페이지 보정 로직 추가
- URL 파라미터를 통해 페이지 번호와 정렬 기준 유지
-변경전
-변경 후
-url 파라미터 적용
반응형 버그 수정 후 테스트 과정 중  mobile 사이즈에서 카드를 클릭하여 피드로 이동 후 pc사이즈로 변경하고 뒤로가기를 누르면
페이지 번호를 기억하여 해당 페이지로 돌아가는 과정에서 질문자가 있는 카드로 돌아가는것이 아닌 단순 페이지 번호로 돌아가고있습니다. 추후에 질문자id를 url파라미터에 추가하여 뒤로가기를 누르면 해당 질문자의 페이지로 뒤로갈 수 있게 변경 해보겠습니다.

Refactor(#147): postList 페이지 반응형 버그 수정, url파라미터 적용 리팩토링

---

src/components/ui.js
src/pages/post/components/PostDetailHeader.jsx

- close #161
상세페이지 헤더 - 버튼 공용 컴포넌트로 교체
- [카카오 공유하기 이슈]
공용 컴포넌트를 써서 prop으로 내려주니 shareUtils.js가 들어가 있지 않아 작동하지 않습니다.
그렇다고 공용 컴포넌트에 kakao 스크립트만 추가 하자니 공유하기 스크립트가 흩어져서 유지보수가 힘들 것 같습니다.
의견 부탁드립니다 :)

Feat(#161): 상세페이지 헤더 - 버튼 공용 컴포넌트로 교체

---

src/components/FeedCard/AnswerButton.jsx
src/components/FeedCard/AnswerButton.module.css
src/pages/post/components/PostDetailHeader.jsx
src/pages/post/components/PostDetailHeader.module.css
src/pages/post/components/PostDetailLayout.module.css
src/pages/post/components/Questions.jsx

- close #176 
- close #180
- <답변하러가기> 버튼 상세페이지 헤더로 이동
- 상세페이지 헤더에 생성일 시간 표시 기능 추가

Feat(#176,#180): 답변하러가기 버튼 상세페이지 헤더로 변경, 생성일 추가

---

src/pages/post/components/useQuestionHandlers.js

- close #178 
피드 삭제시 confirm을 통해 삭제 유무를 확인후 진행하도록 개선

Feat(#178): 피드삭제시 한번더 확인 기능 추가

---

src/components/Modal/Modal.jsx
src/components/Modal/usePreventScroll.js
src/pages/sample/components/SolSample.jsx

- close #185
- 공용 컴포넌트 modal 고도화
- useRef, forwardRef, useImperativeHandle 를 사용
https://github.com/user-attachments/assets/44006b9e-cf72-490b-8c16-9093821902d7
- 모달창이 열릴 때 root 쪽에 넣어지면서 스크롤이 상단으로 올라갑니다
- 해결 방법을 찾고 있으나 찾는 시간이 길어져 의견을 듣고 싶습니다 🥲

Refector(#185): 공용 컴포넌트 modal 개선

---

src/components/UserCard/UserCard.module.css
src/pages/post/PostListPage.jsx
src/pages/post/components/PostList.jsx
src/pages/post/components/PostList.module.css
src/pages/post/components/PostListHeader.jsx
src/pages/post/components/itemPerPage.js

- close #172 
- itemsPerPage 변경 시 현재 페이지의 첫 번째 아이템 인덱스를 기준으로 페이지를 재계산하도록 로직 수정.
- 화면 사이즈에 따라 정확한 페이지 번호가 유지되도록 페이지 보정 로직 추가.
- 정렬 기준 변경 시 URL 파라미터를 통해 페이지를 1번으로 초기화.
- ul과 li 구조 마크업 적용 (시맨틱 마크업 개선).
- 스타일 상 충돌을 최소화하기 위해 UserCard 내부 CSS와 부모 컨테이너 CSS 분리 관리.
- PC/태블릿/모바일 해상도에 따라 4단 → 3단 → 2단으로 카드 레이아웃 조정.
- 카드의 최소 너비 186px 유지, 최대 너비 유연 확장 (minmax 적용).
- 모바일에서 gap을 줄이고 좌우 여백을 24px로 조정.
아직도 미세하게 스타일과 반응형에서 오류가 있는것같습니다. 최종 수정까지 하려 했으나 우선 큰 오류부터 잡고 추가적으로 수정하겠습니다.

Refactor(#172): 반응형 페이지네이션 오류 수정 및 카드리스트 마크업 수정, css 수정

---

src/components/Button/FloatingButton.jsx
src/components/Button/FloatingButton.module.css
src/components/Button/LinkButton.jsx
src/components/Button/LinkButton.module.css
src/components/Button/ShareButton.jsx
src/pages/sample/components/RinaSample.jsx
src/pages/sample/components/RinaSample.module.css

- close #이슈번호
- responsive props를 추가하여, responsive=true일 경우에반 반응형으로 생성됩니다.

Refactor(#200) button 컴포넌트 수정

---

src/components/FeedCard/AnswerMenu.jsx
src/components/FeedCard/FeedCard.jsx
src/pages/post/components/useQuestion.js
src/pages/post/components/useQuestionHandlers.js

- close #216 
답변페이지에서, 질문을 개별로 삭제할 수 있는 기능을 만들었습니다.
- 삭제가 두개가 있어서 명확하게 '질문삭제','답변삭제'로 이름을 변경해두었어요 (케밥메뉴)

Feat(#216): 개별 질문 삭제 기능 추가

---

src/util/format.js

- close #213 
분명 어제까지, 답변 작성을 하면 날아오는 데이터의 작성일이 '몇초후'라고 미래로 떳었는데,
오늘은 괜찮네요. 그래도 혹시 몰라서 데이터의 작성일이 지금이거나, 미래이면 '방금전'이라고 바꿔서 나가도록 수정해두었습니다.

Fix(#213): 답변 작성시간이 미래로 나오는 현상 수정 (몇초후)

---

src/components/Layout/Layout.jsx
src/components/Layout/Loading.module.css
src/components/Layout/Loding.jsx

- close #222 
새로고침이나, url직접접근에서는 hydrate fallback ui로 로딩을 구현했고
앱내에서 라우트 이동시에 상세페이지 접근할때, loader에서 데이터를 받는동안 화면이 멈춘듯하게 보이는 부분을
로딩ui추가로 개선했습니다.

Feat(#222): 라우터로 상세페이지 접근시 loader로 인한 로딩 ui보여주기

---

src/components/Button/LinkButton.module.css
src/pages/post/components/PostListHeader.jsx
src/pages/post/components/PostListHeader.module.css

- close #224 
- 피그마 시안을 토대로 피드 리스트 페이지 헤더 반응형 수정 
- 버튼 responsive 동작이 안되는 것을 css 우선순위 조정을 통해 해결하였습니다.
- PC
- Tablet
- Mobile

Refactor(#224) 피드 리스트 페이지헤더  반응형 수정

---

src/pages/post/components/useLike.js

- close #219 
좋아요, 싫어요를 누를때, 낙관적 업데이트를 하기전에 이전 데이터 캐쉬를 불러오는 과정에 사용하는
쿼리키를 변경 
- 정확하게 ['questions', subjectId]로 변경

Fix(#219): 좋아요, 싫어요 mutation에 쓰인 쿼리키 수정

---

src/components/UserCard/UserCard.module.css

- close #247 
- 유저카드 배경색을 추가했습니다.

Design(#247): 유저카드에 배경색 삽입

---

src/pages/post/components/useQuestion.js

- close #244 
답변자가 질문 개별 삭제시, 성공 피드백 추가했습니다.
(오류시의 피드백은 작성되었어서, 성공만 추가했습니다.)

Fix(#244): 질문 개별 삭제시, 성공 피드백 추가

---

src/components/FeedCard/AnswerForm.jsx
src/pages/post/components/useQuestion.js

- close #265 
- 질문의 좋아요, 싫어요 리액션의 낙관적 업데이트 개선
- 기존에는 낙관적업데이트 이후에, 실제 데이터로 한번 더 교체를 해줬는데, 불필요해보여서 삭제 (오히려 더 방해가됨) 
- 답변 수정시 불필요한 요청 수정
- 수정된 내용이 없을경우에 제출 버튼도 비활성화 및 제출시에도 한번 더 변경사항이 있는지 체크하도록 개선

Fix(#265): 리액션 및 답변수정 사용자 경험 개선

---

src/components/FeedCard/Answer.jsx
src/components/FeedCard/FeedCard.jsx
src/components/Toast/Toast.jsx
src/pages/post/PostAnswerPage.jsx
src/pages/post/components/useAnswer.js
src/pages/post/components/useQuestion.js

- close #271 
- 질문 개별삭제후, 전체 질문갯수가 업데이트 안되는 현상 수정
- 질문의 케밥메뉴에 수정이 불가능한 상태 (미답변)이면 버튼 비활성화 추가
- 리액트쿼리 setQueriesData 수정 -> setQueryData : 공부를 더 해보니 이게 맞는것 같네요
- 불필요한 코드 삭제

Fix(#271): 질문카드 개선

---

src/components/FeedCard/QuestionForm.jsx
src/components/Modal/Modal.jsx
src/components/Modal/usePreventScroll.js

- close #286 
- 질문 작성시 상단으로 스크롤을 복구해야하는데, 모달의 스크롤 위치 기억과 충돌로 코드 개선
- 모달컴포넌트에 강제 스크롤 0으로 복구하면서 닫히는 메소드 추가
-

Fix(#286): 모달 메소드 추가 (강제 스크롤 0으로 복구하면서 닫히는 메소드 추가)

---

src/components/FeedCard/AnswerButton.jsx
src/context/FeedContext.jsx
src/pages/post/PostAnswerPage.jsx
src/pages/post/PostDetailPage.jsx
src/pages/post/components/ProtectedRoute.jsx

- close #296 
주말에 리액트쿼리키에 대해서 조금더 공부하다가, 쿼리키로 params의 값을 쓸때 type이 다르면 안되는걸 알게되어서
긴급하게 수정했습니다.
- 기존에는 useparams에서 받아온 string 타입의 id를 바로 사용 (데이터와 비교를 해야할경우에만 숫자로 변환, 어차피 요청은 문자열로 되니 신경 안썻음)
- 그래도 정확한 쿼리키값을 위해서는 처음부터 데이터의 원래의 type과 동일하게 관리하는것이 맞다고 판단되어 number타입으로 미리 변환해서 프로젝트 내에서 사용하도록 변경

Fix(#296): useParams의 id를 number타입으로 변환후 필요한곳에 전달하도록 변경

---

src/constants/messages.js
src/pages/main/components/IntroForm.jsx

- close #298
- 사용자가 "이미 생성한 피드가 있나요?" 버튼을 눌렀을때 생성한 피드가 없으면 Notify가 나타나 없음을 알리는 기능.
https://github.com/user-attachments/assets/0c6b98f0-7075-4302-a412-03a2f558b54b
- feeds에 데이터가 없어야 정확하게 테스트할 수 있는데.. 제가 테스트하면서 작성한 피드들을 손으로도 다 삭제하고 api들어가서도 다 삭제했는데
오류인지 뭔지 2개가 삭제가 안되더라고요?? 페이지 들어가면 에러페이지뜨고 api 들어가서 id로 찾아도 데이터 없다 뜨는데 이상하게 계속 남아 있더라고요. 로컬스토리지에 남아있는건지... 피드데이터가 없으신분이 한번 테스트해봐야 제대로 되는지 알 것 같습니다

Refactor(#298): 생성한 피드가 없을때 Notify컴포넌트 사용하여 없음을 알리는 기능 개선

---

src/pages/post/components/PostDetailHeader.jsx

- close #316
카카오 sdk 탑재부분에 같이 들어가 있어서
다른 페이지 갔을 때 sharekakao(name)이 바뀌지 않는 이슈 해결

Fix: 다른 페이지에서 sharekakao(name) 안 바뀌는 이슈 해결
