- .gitignore
- netlify.toml
- close #3
- netlify redirect 설정
- PR을 작성하고 조금? 조금오래? 기다리면 이렇게 netlify에서 배포된 preview가 bot이 적습니다.
> Chore(#3): 배포셋팅

- package-lock.json
- package.json
- src/App.jsx
- src/components/Layout/Layout.jsx
- src/components/Layout/index.js
- src/pages/ErrorPage.jsx
- src/pages/main/MainPage.jsx
- src/pages/main/components/Sample.jsx
- src/pages/main/components/Sample.module.css
- src/pages/post/PostAnswerPage.jsx
- src/pages/post/PostDetailPage.jsx
- src/pages/post/PostListPage.jsx
- src/pages/post/components/Sample.jsx
- src/pages/post/components/Sample.module.css
- src/router.jsx
- close #12 
- 리액트 라우터 셋팅
- 프로젝트 샘플 페이지 작성
- 메인 : '/'
- 리스트 : '/list'
- 피드 : 'post/3'
- 답변 : 'post/3/answer'
- 페이지 라우팅 설정하면서 페이지내용은 샘플로 넣어두었습니다.
> Chore(#12): 페이지 라우팅 셋팅

- src/main.jsx
- src/pages/sample/SamplePage.jsx
- src/pages/sample/SamplePage.module.css
- src/pages/sample/components/ChankiSample.jsx
- src/pages/sample/components/CharieSample.jsx
- src/pages/sample/components/GyeonSample.jsx
- src/pages/sample/components/RinaSample.jsx
- src/pages/sample/components/SolSample.jsx
- src/router.jsx
- close #26 
공용컴포넌트 작업결과를 보여줄수있는 샘플페이지를 만들었어요
각자이름의 컴포넌트안에서 만드는 공용컴포넌트 샘플을 테스트해보거나, 전시해주세요
(storybook은 지금 배워서하기에는 어려운것같아요)
> Feat(#26): 공용 컴포넌트 sample page 작업

- src/assets/css/global.css
- src/assets/css/reset.css
- close #37
- reset : 폰트 임포트 방식으로 변경
- global : 모든 태그에 box-sizing 추가
- reset.css / global.css 에 추가하고 싶은 부분 있으면 자유롭게 추가해주세요😊
> Feat: reset css, global css 수정

- src/components/Input/InputField.module.css
- src/components/Input/InputTextarea.jsx
- src/components/Input/InputTextarea.module.css
- src/pages/sample/components/GyeonSample.jsx
- close #46 
- 공용으로 사용할 수 있는 InputTextarea 구현
- focus 전:
- focus 후:
- vlaue, onChange, placeholder, rows(텍스트 줄 수), maxLength(최대 글자 수) prop들을 받을 수 있습니다
> Feat(#46): InputTextarea 공용컴포넌트 개발

- src/components/Icon/Icon.jsx
- close #42 
svg icon의 컬러를 더 다양하게 쓸 수 있도록 개선했어요.
따로 color를 지정하지 않으면 폰트칼라를 따라가도록 했어요
> Feat(#52): svg icon 컴포넌트 색상 개선

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/MoreMenu.jsx
- src/components/Dropdown/MoreMenu.module.css
- src/components/Dropdown/Select.jsx
- src/components/Dropdown/Select.module.css
- src/components/Dropdown/index.js
- src/pages/sample/components/ChankiSample.jsx
- close #51 
- dropdown 컴포넌트
- select 컴포넌트
- ~~kebab 컴포넌트~~ MoreMenu 컴포넌트 
https://github.com/user-attachments/assets/5dc9cd29-f564-4bfa-a739-aa5a32980736
- Dropdown은 trigger를 누르면 list가 열리고 닫히는 역활만하는 스타일링이 없는 headless ui처럼 만들었습니다.
- 이 Dropdown을 활용해서 Select, MoreMenu 컴포넌트를 만들었어요.
- 혹시나 다른 모양이 드롭다운 기능을 만들어야되면, Dropdown컴포넌트를 활용해서 제작하면 됩니다.
- 누를때 펼쳐지는 느낌으로 애니메이션도 넣어봤습니다.
> Feat(#51): dropdown 컴포넌트 작업

- src/pages/main/MainPage.jsx
- src/pages/main/MainPage.module.css
- src/pages/post/PostAnswerPage.jsx
- src/pages/post/PostDetailPage.jsx
- src/pages/post/PostListPage.jsx
- src/pages/post/components/PostDetailHeader.jsx
- src/pages/post/components/PostDetailHeader.module.css
- src/pages/post/components/PostDetailLayout.jsx
- src/pages/post/components/PostDetailLayout.module.css
- src/pages/post/components/PostList.jsx
- src/pages/post/components/PostList.module.css
- src/pages/post/components/PostListHeader.jsx
- src/pages/post/components/PostListHeader.module.css
- src/pages/post/components/PostListLayout.jsx
- src/pages/post/components/PostListLayout.module.css
- src/pages/post/components/Questions.jsx
- src/pages/post/components/Questions.module.css
- src/router.jsx
- close #50 
페이지 작업 시작전에 작업구역을 셋팅했어요
> Feat(#50): 페이지 작업구역 셋팅

- src/components/Input/index.js
- src/pages/sample/components/GyeonSample.jsx
- close #63 
- Input 컴포넌트들 바렐패턴 작업
> Refactor(#63): Input 컴포넌트들 바렐패턴 작업

- src/pages/ErrorPage.jsx
- src/pages/post/loader/PostDetailLoader.js
> Fix(#69): loader에 id paramter 추가

- src/pages/sample/components/GyeonSample.jsx
- close #71 
Gyeon샘플페이지에 userCard import문 추가
> Fix(#71): userCard import문 부재로 인한 오류 해결(import문 추가)

- package-lock.json
- package.json
- src/App.jsx
- close #73 
- 리액트쿼리 패키지 설치
-  queryclient 및 provider 셋팅
- 일단 셋팅을 해두었는데, 사용법을 공부해보신다음 써보실분들은 한번 써보시면 될 것 같아요
> Feat(#73): react query 셋팅

- src/assets/css/reset.css
- close #78 
input과 textarea 초기화 스타일 지정했습니다.
> Design(#78): reset css 추가건 (input, textarea)

- src/components/ui.js
- src/pages/post/components/PostList.jsx
- src/pages/post/components/PostList.module.css
- close #90 
- 질문자 목록 조회 api 데이터정보를 UserCard 컴포넌트에 연결하여 기능 구현
- 페이지 내부 UserCard 스타일링 수정
- 
- css에서 반응형 설정을 안했는데 달라지는건 user컴포넌트 내부 css 때문인지  페이지 css에 그리드설정을 해서 그런건지  모르겠네요...
- 스타일링 부분이 많이 모자란거같지만 우선 pr올리고 css수정은 추가적으로 하겠습니다.
> Feat(#90): PostList 페이지 UserCard 컴포넌트 연결 구현

- src/pages/main/MainPage.jsx
- src/pages/main/MainPage.module.css
- src/pages/main/components/MainLogo.module.css
- close #88 
- 답변하러 가기 버튼에 Link를 활용하여 /list 페이지로 이동.
https://github.com/user-attachments/assets/b40ca6e9-9cb6-4ae0-9330-b7145bfc99e7
- 공용 컴포넌트 완료시 버튼 교체 필요
> Feat(#88): 메인페이지 답변하러가기 Link 구현

- src/assets/css/reset.css
- close #115
- reset css 수정 (시맨틱태그 box-sizing 추가)
> Design(#115): reset css 수정 (시맨틱태그 box-sizing 추가)

- src/components/FeedCard/FeedCardList.module.css
- src/components/FeedCard/FeedDeleteButton.jsx
- src/components/FeedCard/FeedDeleteButton.module.css
- src/components/FeedCard/index.js
- src/pages/post/PostAnswerPage.jsx
- src/pages/post/PostDetailPage.jsx
- src/pages/post/components/Questions.jsx
- src/pages/post/components/useAnswer.js
- src/pages/post/components/useQuestions.js
- close #114 
답변페이지에서 피드 삭제 버튼 추가했습니다.
> Feat(#114) : 피드 삭제 버튼 추가

- src/App.jsx
- src/context/FeedContext.jsx
- src/pages/post/components/Questions.jsx
- src/pages/post/components/useAnswer.js
- close #122 
- context안에서 유섭님이 제작하신 api호출 함수들 사용하여 피드생성, 피드삭제를 구현해두었어요
- 생성, 삭제시 마다 로컬스토리지에 저장이 됩니다.
- context value 정보
- isLoading
- feeds : 브라우저에 가지고있는 피드정보 리스트
- createFeed : 피드생성 함수 (이름을 전달하면됩니다.)
- removeFeed : 피드삭제 함수 (피드아이디 전달)
- hasFeed : 브라우저에 가지고 있는 피드아이디인지 판별 (피드아이디 전달)
- 기연님, 리나님 : 방생성 및 내 브라우저에 가지고 있는 방정보리스트는 이 context로 조회하세요
- const { isLoading, feeds, createFeed, removeFeed, hasFeed } = useFeed();
> Feat(#122): useFeed Context 생성 (방생성, 삭제 전역 관리)

- src/pages/post/components/PostDetailHeader.jsx
- src/util/shareUtils.js
- close #127
- 현재 페이지 URL 복사 기능 구현
https://github.com/user-attachments/assets/9869a8d0-f9ea-4cbd-a238-93386862229f
- toast 실행 함수를 좀 더 편하게 불러올 수 있는 로직을 고민해보겠습니다.
> Feat(#127): 현재 페이지 URL 복사 기능 개발

- src/components/Button/LinkButton.module.css
- src/pages/post/PostListPage.jsx
- src/pages/post/components/PostListHeader.jsx
- src/pages/post/components/PostListHeader.module.css
- src/pages/post/components/PostListLayout.jsx
- close #이슈번호
- 피드 리스트 페이지의 헤더 레이아웃을 구현하였습니다.
- LinkButton css 를 수정하였습니다. (중앙 정렬, 갭 추가)
> Feat(#137) post list header 

- src/pages/post/components/PostPageHydrateFallback.jsx
- src/pages/post/components/PostPageHydrateFallback.module.css
- src/pages/post/loader/PostDetailLoader.js
- src/router.jsx
- close #132 
질문, 답변 페이지에 접근시 실행되는 loader 내부 개선 및 첫 접근또는 새로고침에서 보이는 hydrate fallback ui 작업
- loader 내부 fetching을 유섭님이 작업하신 api 함수로 변경
- hydrate fallback ui 작업 (피드정보를 가져오는중입니다. 멘트 노출)
> Feat(#132): post페이지 loader 개선

- package-lock.json
- package.json
- src/components/FeedCard/FeedCardList.jsx
- src/components/FeedCard/QuestionForm.jsx
- close #141 
질문 카드에 애니메이션 효과를 넣엇습니다.
- 질문작성시 스크롤 상단으로 이동하도록 추가했습니다.
https://github.com/user-attachments/assets/94aee2b3-d5ad-4660-a3ab-dab2b78940b9
https://motion.dev/docs/react-quick-start
혹시나 사용해보고 싶으시면 공식문서 보시면됩니다.
> Feat(#141): 질문카드 애니메이션 추가

- src/pages/post/components/PostList.jsx
- close #144 
UserCard 컴포넌트에 Link 컴포넌트 사용하여 클릭 시 질문목록으로 이동하기 기능 구현
우선 기능적으로만 구현하였습니다.
혹시 추가적으로 수정사항이 있는지 말씀해주시거나 제가 확인해보고 아쉬운부분이 있으면 추가하겠습니다.
> Feat(#144) : postList 페이지 UserCard 클릭 시 질문목록 페이지 이동 기능 추가

- src/pages/main/MainPage.module.css
> Design(#151): 메인페이지 배경 변경

- src/pages/main/MainPage.jsx
- src/pages/main/MainPage.module.css
- src/pages/main/components/MainPageInputForm.jsx
- src/pages/main/components/MainPageInputForm.module.css
- close #111
- close #136 
https://github.com/user-attachments/assets/1c44723a-c279-4b36-818f-08639b6f6738
- localStorage에 방문한 사람들 저장
- 저장된 데이터들 출력 결과
- 질문 받기 버튼 text가 중앙 정렬되어야할 것 같습니다, 화면 사이즈가 작아져도 버튼의 높이는 그대로여야 하는데 변화가 있는 것 같습니다
- localStorage에 저장되는 것이 요구사항에 맞게 됐는지 확인 부탁드립니다!
> Feat(#111, #136): [메인페이지] 입력폼구현, 답변하러 가기 버튼 교체

- src/pages/post/components/useQuestion.js
- close #154 
질문작성후 불필요하게 데이터를 다시 조회하는 일을 방지하려고, 서버에서 반환된 데이터로 내부 state를 변경했는데
전체 카운트수도 증가하도록 수정했어요
> Fix(#154): 질문작성후 전체 갯수 증가하도록 수정

- src/pages/post/components/ProtectedRoute.jsx
- src/router.jsx
- close #124  
피드정보를 로컬스토리지에 가지고 있으면 답변페이지로 접근가능하도록 보호했습니다.
- 이전에 작업했는데, revert를 해서 다시 올립니다
> Feat(#124): Protect route 추가

- README.md
> Chore: README.md 업데이트

- src/components/FeedCard/FeedCardList.jsx
- src/pages/post/components/useAnswer.js
- src/pages/post/components/useLike.js
- src/pages/post/components/useQuestion.js
- src/pages/post/components/useQuestionHandlers.js
- src/pages/post/components/useQuestions.js
- close #167 
애니메이션 버그인줄 알았는데, 리액트쿼리의 쿼리키를 자세하게 안적어서 그랬습니다.
(이전데이터가 남아있는 현상수정)
> Fix(#167): 이전 데이터 남아있는 현상 및 애니메이션 수정

- src/components/Button/FloatingButton.jsx
- src/components/Button/FloatingButton.module.css
- src/components/Button/LinkButton.module.css
- src/components/Button/ShareButton.jsx
- src/components/Button/ShareButton.module.css
- src/pages/post/components/PostListHeader.jsx
- src/pages/sample/components/RinaSample.jsx
- src/pages/sample/components/RinaSample.module.css
- close #이슈번호
- 버튼 수정하였습니다.
- 버튼 샘플 페이지를 수정하였습니다.
> Refactor(#145) button fix

- src/pages/main/MainPage.jsx
- src/pages/main/MainPage.module.css
- close #이슈번호
- 로티를 position: absolute로 설정하고 bottom:0에 배치.
- z-index를 입력폼에 설정하여 로티보다 우선순위를 높게함.
> Feat/159/메인페이지 로티 추가

- src/pages/main/MainPage.jsx
> Refactor(#171): onClick으로 useNavigate활용하여 링크이동

- src/assets/css/global.css
- src/components/FeedCard/Answer.module.css
- src/components/FeedCard/AnswerForm.jsx
- src/components/FeedCard/AnswerForm.module.css
- src/components/FeedCard/FeedCardList.module.css
- src/components/FeedCard/FeedCardWrapper.module.css
- src/components/FeedCard/FeedDeleteButton.jsx
- src/components/FeedCard/FeedListHeader.module.css
- src/components/FeedCard/QuestionForm.jsx
- src/components/FeedCard/QuestionForm.module.css
- close #143 
- 공용 버튼 컴포넌트로 교체
- 상단 질문카운트 타이틀 글자 색상 추가
- 질문 카드 리스트 모바일에서 간격 줄이기
- 이름이 매우 길때 답변카드에서 말줄임 넣기
- 이름이 매우 길때 작성일이 한줄로 나올수 있게 수정
> Design(#143): 상세페이지 질문카드, 답변카드 스타일 개선 및 공용 버튼 교체

- src/components/Modal/Modal.jsx
- close #182
모달창 애니메이션 적용
https://github.com/user-attachments/assets/2ff463c3-4ec0-4c25-bf90-c757dfe6dd94
> Feat(#182): 모달 애니메이션 적용

- src/components/UserCard/UserCard.jsx
- src/components/UserCard/UserCard.module.css
- src/pages/sample/components/GyeonSample.jsx
- close #174 
- 유저의 이름이 한줄 이상일때 말줄임으로 한줄로 표현
- 유저의 이름 hover시 색변경
https://github.com/user-attachments/assets/26683539-dad0-4ea3-8441-86a4215afffe
- 처음에 이름을 onClick시 클래스를 추가 하는 방식으로 구현했는데 클릭하면 피드페이지로 넘어가더라구요. 그래서 이걸 해결하려다 hover로 하면 코드도 간략해지는 것 같아서 hover로 구현했습니다
> Refactor: UserCard 이름이 한줄 이상넘어가면 말줄임 기능

- src/components/FeedCard/QuestionForm.jsx
- close #190 
공용모달 개선관련하여 대응 업데이트
> Refactor(#190): 공용 모달 수정으로 인한 코드 변경

- src/pages/post/components/PostDetailHeader.module.css
- src/pages/post/components/PostDetailLayout.module.css
- close #193
상세페이지 헤더 유저이름 길이 조절
> Design(#193): 상세페이지 헤더 유저이름 길이 조절

- src/components/Button/FloatingButton.jsx
> refactor(#205) 버튼 수정

- src/pages/post/components/PostList.jsx
- close #209 
-API 호출이 진행 중일 때 중복 호출을 방지하도록 loading 상태를 도입.
-loadSubjects 함수를 useCallback으로 메모이제이션하여 불필요한 함수 재생성을 방지.
-API 호출이 필요한 상태(페이지, 정렬, 항목 수)가 변경될 때만 요청되도록 정리
리액트쿼리 적용전 우선 무한 요청을 막기위해 추가해봤습니다. 
테스트전 무한으로 요청을 하는게 발견이 되어 적용 후에는 페이지변경, 정렬변경, 화면리사이즈 시에만 요청하는거같아요
> Feat(#209) 질문자목록 페이지 무한패칭 방지 최적화 기능 추가

- src/components/MyFeeds/MyFeeds.jsx
- src/components/MyFeeds/MyFeeds.module.css
- src/components/MyFeeds/MyFeedsButton.jsx
- src/components/MyFeeds/MyFeedsButton.module.css
- src/components/MyFeeds/index.js
- src/pages/main/MainPage.jsx
- src/pages/post/components/PostListHeader.jsx
- close #211 
메인페이지 및 리스트에서 사용할 '이미 생성한 피드'를 조회할 UI 제작
- 생성한 피드 모달 컴포넌트작업
- 메인에 연결
- 리스트페이지에 연결
> Feat(#211): 이미 생성한 피드 조회 UI 작업

- src/components/Input/InputField.jsx
- src/components/Input/InputTextarea.jsx
- src/pages/main/components/MainPageInputForm.jsx
- close #199 
- clsx를 활용하여 공용 컴포넌트를 사용하는 사용자가 동적으로 className을 추가할 수 있게 함.
> Refactor(#199): inputField, InputTextarea clsx활용하여 동적으로 css추가 가능

- src/components/Input/InputTextarea.module.css
- close #218 
- InputTextarea에 투명 border를 추가하여 들썩임 방지
https://github.com/user-attachments/assets/e097f94a-7d84-4371-9906-c2510fdb8765
> Design(#218): InputTextarea 투명 border 추가

- src/pages/main/MainPage.jsx
- close #221
- responsive prop 적용
> Refactor(#221): 질문하러 가기 버튼 responsive 적용

- src/App.jsx
- close #231 
상세페이지에서 사용자의 이름으로 title등 메타태그를 변경한것이
메인이나 리스트페이지로 돌아올때 그대로 남아있는 현상을 수정했습니다.
- 루트레벨에서 기본 리액트 헬멧 설정해주었어요.
> fix(#231): seo 버그 수정

- src/components/FeedCard/AnswerButton.module.css
- src/components/Modal/Modal.module.css
- src/pages/post/components/PostDetailHeader.module.css
- src/pages/post/components/PostDetailLayout.module.css
- close #215
반응형 css 및 배경 이슈 해결
https://github.com/user-attachments/assets/0674ae65-8798-49ac-8734-fcd372f3d20f
> Design(#215): 반응형 css 및 배경 이슈 해결

- src/components/FeedCard/AnswerForm.jsx
- src/components/FeedCard/QuestionForm.jsx
- close #234 
값이 없으면 disabled가 설정되어 제출을 못하지만
억지로 disabled를 지우게 되더라도 막을수 있게 개선했어요
> Feat/(#234): 질문 작성, 답변 작성(수정)에 validation 추가

- src/pages/main/MainPage.module.css
- close #228
- 로티로인한 버튼클릭이 안되는 것을  z-index 사용해서  수정
https://github.com/user-attachments/assets/024c3ac6-8bcb-4be4-85fa-c04174f878d6
> Refactor(#228): 헤더의 링크버튼 z-index:1 설정

- index.html
- src/util/shareUtils.js
- close #189
페이스북 공유하기 로그인 체크 추가
> Feat(#189): 페이스북 공유하기 로그인 체크 추가

- src/components/Pagination/Pagination.jsx
- src/components/Pagination/Pagination.module.css
- close #202 
- pagination 이동하기 버튼 기존 텍스트 ">"에서 icon 컴포넌트 사용하여 변경
- pagination  ul , li 형식으로 마크업 변경
- css 스타일 수정
> Feat (#202) : pagination 컴포넌트 이동 화살표 icon 컴포넌트 사용 및 마크업 개선

- src/components/FeedCard/AnswerForm.jsx
- src/components/FeedCard/AnswerForm.module.css
- close #246 
답변폼 버튼 배치 스타일 수정했습니다. 가로로 배치되게 했습니다.
> Design(#246): 답변폼 버튼 배치 스타일 수정

- src/components/MyFeeds/MyFeedsButton.module.css
- close #242 
메인에 있는 '이미 생성한 피드가 있나요?' 버튼에 밑줄을 삭제했습니다.
(하버 효과도있는데 밑줄까지 있으니 어색하네욤)
> Design(#242): '이미 생성한 피드가 있나요?' 버튼에 밑줄을 삭제

- index.html
- package-lock.json
- package.json
- src/pages/post/components/PostDetailHeader.jsx
- src/util/shareUtils.js
> Feat(#240): 페이스북 공유하기 개선

- src/components/Dropdown/Select.module.css
- close #251 
셀렉트 컴포넌트에 배경색 추가했습니다.
> Design(#251): 셀렉트 컴포넌트에 배경색 추가

- src/components/Pagination/Pagination.module.css
- src/pages/post/components/PostList.module.css
- close #253 
- 높이값 삭제 및 하단 여백값 조정
> Refactor(#253) : 페이지네이션 마진병합 문제 해결을 위한 css 수정

- src/components/UserCard/UserCard.jsx
- src/pages/main/components/MainPageInputForm.jsx
- close #250
- 이름값의 변수가 참일때 일반 state 변수를 가져오는걸 확인. 유효성 검사가된 trimmedName으로 변경.
> Fix(#250): 유효성 검사 변수 변경

- src/pages/main/MainPage.jsx
- close #259
- 클릭으로 로티 재생제어 기능 삭제
> Refactor(#259): 메인페이지 Lottie 클릭으로 재생제어 삭제

- src/components/Badge/Badge.jsx
- src/components/Badge/Badge.module.css
- close #275
- clsx 사용해서 코드 단순화
> Refactor(#275): badge 리팩토링

- jsconfig.json
- src/components/FeedCard/AnswerForm.jsx
- src/components/FeedCard/FeedCard.jsx
- src/components/FeedCard/QuestionForm.jsx
- src/constants/messages.js
- src/pages/main/components/MainPageInputForm.jsx
- src/pages/post/PostAnswerPage.jsx
- src/pages/post/components/ProtectedRoute.jsx
- vite.config.js
- close #274 
시스템 메시지들을 상수화했습니다.
기연님과 한솔님의 작업페이지도 수정파일에 들어있어요. 충돌 꼭 확인하셔야합니당
> Refactor(#274): 시스템 메세지 상수화

- src/pages/post/PostListPage.jsx
- src/pages/post/components/PostList.jsx
- src/pages/post/components/PostList.module.css
- src/pages/post/components/PostListError.jsx
- src/pages/post/components/PostListError.module.css
- src/pages/post/components/PostListFilter.jsx
- src/pages/post/components/PostListFilter.module.css
- src/pages/post/components/PostListLoading.jsx
- src/pages/post/components/PostListLoading.module.css
- src/pages/post/components/PostListPagination.jsx
- src/pages/post/components/PostListPagination.module.css
- src/pages/post/components/PostListWrapper.jsx
- src/pages/post/components/PostListWrapper.module.css
- close #266 
1. 에러/로딩 처리
- 데이터 로딩/에러/빈 상태 처리를 명확히 구분.
- 잘못된 URL 입력 시 에러 메시지 출력(PostListError 컴포넌트 활용).
- React Query의 `useErrorBoundary: false` 설정으로 전역 에러 방지.
2. 로딩 UI 개선
- PostListLoading 컴포넌트를 활용해 로딩 중 스피너 표시.
3. 데이터 유효성 검증
- URL 파라미터(page, sort)의 유효성 검증 추가.
- 잘못된 page 또는 sort 값 입력 시 사용자에게 에러 메시지 표시.
<로딩 화면>
<잘못된 정렬값 url 입력 >
<잘못된 페이지번호 url 입력>
postlist 컴포넌트 분리 리팩토링을 하려 했으나 시간 부족으로 인해 우선 에러/로딩처리만 작업 후 올리게 되었습니다...
> Refactor(#266): 질문자 리스트 에러/로딩 독립적 처리 수정

- README.md
- close #280
- 기술스택, 폴더 구조, 팀 노션 링크 추가
> Doc: Readme 수정

- src/components/Button/LinkButton.jsx
- src/components/Button/ShareButton.jsx
- src/pages/post/components/PostListHeader.jsx
- src/pages/post/components/PostListHeader.module.css
- close #273 
- 각 컴포넌트 별 어떤 목적의 컴포넌트인지 설명 주석을 추가하였습니다.
- 각 컴포넌트가 받는 각각의 props에 대한 설명을 추가하였습니다.
추가로 수정해야할 것이 있다면 말씀 부탁드립니다..!
> Refactor(#273) 코드 주석 정리

- src/pages/post/PostAnswerPage.jsx
- close #287 
피드삭제후 메인으로 왔을때 부자연스러운 ux 개선
- 새로고침하면서 메인으로 가도록 개선
- (기존) 메인으로 이동후 새로고침
-
> Fix(#287): 질문삭제후 리다이렉션 개선

- src/components/FeedCard/QuestionForm.jsx
- src/components/Modal/Modal.jsx
- src/components/Modal/usePreventScroll.js
- src/pages/post/PostAnswerPage.jsx
> 21일 점검 배포 2차

- README.md
> 21일 리드미 수정 배포

- src/router.jsx
- close #292 
월요일 코드리뷰 대비해서 코드보는중인데, 
이해하기 어려운 라우팅 구조 더 쉽게 변경해보았어요
> Refactor(#292): 라우트 작성 개선

- src/context/FeedContext.jsx
- src/pages/post/PostDetailPage.jsx
- src/pages/post/components/useSubject.js
- close #294 
최근 방문 피드 기능 개발취소로 인해 관련 코드 삭제
> Refactor(#294): 최근방문피드 관련 코드 삭제

- src/components/FeedCard/AnswerButton.jsx
- src/constants/messages.js
- src/context/FeedContext.jsx
- src/pages/main/components/IntroForm.jsx
- src/pages/post/PostAnswerPage.jsx
- src/pages/post/PostDetailPage.jsx
- src/pages/post/components/ProtectedRoute.jsx
- src/pages/post/components/useSubject.js
- src/router.jsx
> 23일 월요일 배포

- src/pages/post/PostDetailPage.jsx
- src/pages/post/loader/PostDetailLoader.js
- close #301 
id parameter number타입으로 변환 누락된곳 수정
- 질문리스트 페이지
- 로더
> Fix(#301): id parameter number타입으로 변환 누락된곳 수정

- src/pages/post/components/PostDetailHeader.jsx
- close #305
코드 최종 수정 (코드 정리, 주석 정리)
> Refactor: 코드 최종 수정 (코드 정리, 주석 정리)

- src/pages/post/components/PostListHeader.jsx
- src/pages/post/components/PostListHeader.module.css
- src/pages/post/components/PostListLayout.jsx
- src/pages/post/components/PostListLayout.module.css
- src/pages/post/components/ProtectedRoute.jsx
- src/router.jsx
- close #304  
- 라우팅 파일내, 절대주소를 상대주소로 변경
- 리나님 구역파일 리팩토링 
- 마크업구조를 한솔님과 맞춤
- 주석 삭제
- protected route 컴포넌트 코드 정리
- 주석 삭제
- 임포트 순서 정리
> Refactor(#304): 코드 정리 및 리팩토링(리나님 구역)

- src/service/Axios.js
- close #309 
axios.js 파일 BASEURL설정을 .env파일 환경변수로 변경
> Refactor:(#309): Axios 인스턴스 설정에 환경 변수 적용

- src/components/FeedCard/Reactions.jsx
- src/components/Reaction/Reaction.jsx
- src/components/Reaction/Reaction.module.css
- close #319 
리액션 버튼을 개선했습니다.
- 버튼 텍스트와 아이콘, 컬러등을 전부 props로 전달받아서 유연하게 사용가능하도록 개선했습니다.
- jsdoc 수정
> Refactor(#319): Reaction 컴포넌트 개선

- src/pages/post/components/useQuestions.js
- close #323 
질문, 답변 리스트 패칭훅에서 방어코드 추가
- 패칭한 결과가 null, undefined일수도 있을때의 방어코드 추가
> Refactor(#323): api 통신결과가 null, undefined일 경우를 대비한 방어코드 추가

- src/components/Input/InputField.jsx
- src/components/Input/InputTextarea.jsx
- src/components/UserCard/UserCard.jsx
> Docs(#327): 공용 컴포넌트 InputField, InputTextarea, UserCard Jsdoc 추가

- src/components/FeedCard/Answer.jsx
- src/components/FeedCard/Question.jsx
- src/components/MyFeeds/MyFeeds.jsx
- src/pages/post/components/PostDetailHeader.jsx
- src/util/format.js
- close #321 
fromNow 함수를 순수함수 형태로 변경
- 기존에는 fromNow안에서 new Date를 만들기때문에, 매번 fromNow는 다른값을 내보내게 됩니다.
- 두번째인자로 비교할 날짜를 받아서, 항상 동일한 결과를 반환하도록 수정했습니다.
> Refactor(#321): fromNow 함수를 순수함수 형태로 변경

- src/components/FeedCard/Reactions.jsx
- src/components/Reaction/Reaction.jsx
- close #333 
리액션 컴포넌트 추가개선
- 모양만 제공하는 컴포넌트로 개선
> Refactor(#333): reaction 컴포넌트 추가 개선
